# Site Configuration

# Theme
theme: default

# HTML Language setting
lang: "en"

# Google Analytics tracking id (leave blank if not using)
google_analytics_id: "G-95K6LY8JD8"

# HTML Title
title: "Dogame's Links"

# Avatar image path
avatar: "art/image0.jpeg"

# Name section text
name: "@Dogame"

# Tagline section text
tagline: >-
  Artist & Host of Drawn to the Mic

# List of links (updated to Lucide icon names)
links:
  - link:
      icon: "palette"
      text: "Portfolio"
      url: "/main/"
      alt: "Dogame's Art Portfolio"
      title: "Dogame's Art Portfolio"
      target: "_self"
  - link:
      icon: "twitter"
      text: "Twitter"
      url: "https://twitter.com/Dogame_"
      alt: "Dogame's Twitter"
      title: "Dogame's Twitter"
      target: "_blank"
  - link:
      icon: "instagram"
      text: "Instagram"
      url: "https://www.instagram.com/Dogame__"
      alt: "Dogame's Instagram"
      title: "Dogame's Instagram"
      target: "_blank"
  - link:
      icon: "droplet"
      text: "Drip Haus"
      url: "https://drip.haus/dogame"
      alt: "Dogame's Drip Haus"
      title: "Dogame's Drip Haus"
      target: "_blank"

# Socials (updated to Lucide icon names)
socials:
  - social:
      icon: "instagram"
      url: "https://www.instagram.com/Dogame__"
      title: "Instagram"
      alt: "Dogame's Instagram"
      target: "_blank"
  - social:
      icon: "twitter"
      url: "https://twitter.com/Dogame_"
      title: "Twitter"
      alt: "Dogame's Twitter"
      target: "_blank"
  - social:
      icon: "droplet"
      url: "https://drip.haus/dogame"
      title: "Drip Haus"
      alt: "Dogame's Drip Haus"
      target: "_blank"

# Footer text
footer: >
  Thanks for stopping by!

# Footer copyright message
copyright: >
  © 2025 Dogame.
