name: 'Automatic build'
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'  # Fixed: was missing one asterisk
jobs:
  continuous-delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup Node.js for artwork generation
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2
          bundler-cache: true
          
      - name: Build site with Ruby  
        run: bundle exec ruby "./scaffold.rb"
          
      - name: Generate artwork pages
        run: |
          echo "Installing npm dependencies..."
          npm install
          echo "Generating artwork pages..."
          npm run build
          echo "Artwork generation complete!"
          echo "Checking _output folder:"
          ls -la _output/ || echo "_output folder not found"
          
      - name: Deploy
        run: bash deploy.sh
